# Generated by Django 4.1.7 on 2023-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0002_category_company_alter_jobs_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Data', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
