# Generated by Django 4.2.1 on 2023-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_remove_ocrjobs_data_ocrjobs_contact_ocrjobs_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjobs',
            name='Link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
