# Generated by Django 4.2.1 on 2023-06-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0005_ocrjobs_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjobs',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminSide.category'),
        ),
    ]
