# Generated by Django 4.1.7 on 2023-03-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
