# Generated by Django 4.1.7 on 2023-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='ConfirmPassword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
