# Generated by Django 4.1.7 on 2023-03-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0006_alter_jobseeker_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='LastName',
        ),
    ]
