# Generated by Django 4.1.7 on 2023-03-10 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0008_alter_jobseeker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 chracters')]),
        ),
    ]
