# Generated by Django 4.1.7 on 2023-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0009_alter_jobseeker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
