# Generated by Django 4.1.7 on 2023-03-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0010_alter_jobseeker_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='ConfirmPassword',
        ),
    ]
