# Generated by Django 4.1.7 on 2023-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0013_rename_contact_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='FirstName',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Query',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
