# Generated by Django 4.2.1 on 2023-06-14 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0014_rename_firstname_contactus_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('Job_seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserSide.jobseeker')),
            ],
        ),
    ]
